#pragma once
#pragma pack(push ,1)

struct StatMsgHeader
{
	WORD MsgType;
	WORD RetCode;
};

enum eStatisticProto
{
	STATISTICPROTO_START	=	0x1000,

	GS_REQ_HANDSHAKE,
	ST_ACK_HANDSHAKE,

	GS_NOT_GM_OPERATOR_LOG,
	GS_NOT_PRESENT_LOG,
	GS_NOT_ROOM_STAY_LOG,
	GS_NOT_SING_DETAIL_LOG,
	GS_NOT_VIRTUALMONEY_LOG,

	GS_NOT_ITEM_CHANGE_LOG,
	GS_NOT_ITEM_BUY_LOG,
	GS_NOT_ITEM_CONSUME_LOG,

	GS_NOT_PLAYER_LOGIN_LOG,
	GS_NOT_PLAYER_ONLINE_COUNT,
	GS_NOT_PLAYER_EXPERIENCE_LOG,
	GS_NOT_ROOM_CROWDED_LOG,

	GS_NOT_DETAIL_TRICK_LOG,

	STATISTICPROTO_END,
};

#pragma pack(pop)
